### ISSUE TITLE
Incosistent bullet points in "How to start DSA" page

### ISSUE THREAD

**Issue by gtlsgamr** [developersIndia/wiki#19]
### What Happened?

The bullet points in Video lectures seems to be repeating for the "Aditya Verma" section.
![image](https://user-images.githubusercontent.com/47787284/210130374-9cc98703-4832-40fc-8e6d-18ba71440dcb.png)
It should be just one bullet point, but it is split into two.

### What Browsers Are You Seeing the Problem On?

Firefox, Chrome, Safari, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bhupesh-V** [comment]
Wouild you like to send a PR for this?

**Comment by gtlsgamr** [comment]
@Bhupesh-V Here #20

**Comment by gtlsgamr** [comment]
@Bhupesh-V  Could you please review this? Or someone else from the team? It's a small change.
