### ISSUE TITLE
Why should you start your own blog and How?

### ISSUE THREAD

**Issue by bhavaniravi** [developersIndia/wiki#22]
### Have you read the contributing guidelines for proposing a wiki?

- [X] I have read the contributing guidelines.

### What's this proposal about? What should this wiki cover? Who's the audience?

Most Indian Devs are walking knowledge repositories. They can talk about technology without thought, but we struggle a little bit when it comes to writing.

The article will cover the problems people face when starting their blog and address each of them with steps, examples, and benefits of starting one

### Choose the category for this wiki

Community Guide

### Are you interested in authoring this wiki guide?

Yes

### Code of Conduct

- [X] I agree to follow the community's Code of Conduct

**Comment by Bhupesh-V** [comment]
The proposal is great @bhavaniravi, Folks need to think what they are doing, the best way to do it is by writing their thoughts & learnings!

You can go ahead with working on it 🔥 

A couple of _personal_ suggestion which you can address (IFF possible)
- Building up a Motivation to write (Folks need to have this for long term)
- Having a framework for being consistent (A lot of folks, like me lol, don't write consistently so anything that covers that area can be a cherry on top)
- Finding a niche (the more complex the nice, better the chances of people reading your content)

These are just thoughts, so we don't have to cover them if not possible.

LMK if anything's needed from my side

**Comment by blazete** [comment]
Hey @Bhupesh-V  can i contribute to something

**Comment by Bhupesh-V** [comment]
> Hey @Bhupesh-V can i contribute to something

Hey @blazete thanks for your interest, but this proposal is already assigned to someone.

If you want to contribute a wiki, please head over to https://github.com/developersIndia/wiki/discussions/21 for some ideas. Otherwise, you can also propose a different proposal.
