### ISSUE TITLE
typo in the wiki article : "How to constantly up-skill yourself as a developer"

### ISSUE THREAD

**Issue by gururani-abhishek** [developersIndia/wiki#23]
### What Happened?

In the article, "How to constantly up-skill yourself as a developer" paragraph : Write about what you learn. In Point 1 : it should be 'then' instead of 'than'. 

<img width="1019" alt="Screenshot 2023-04-12 at 22 54 31" src="https://user-images.githubusercontent.com/59947871/231535944-7e0095bb-90ed-4a30-add9-6f04fe8bfe85.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gururani-abhishek** [comment]
I would love to fix this :)

**Comment by Jarmos-san** [comment]
@gururani-abhishek Open a PR linking it to this issue?
