### ISSUE TITLE
support for checking link health in a scheduled manner

### ISSUE THREAD

**Issue by Bhupesh-V** [developersIndia/wiki#26]
### Feature details?

So we have a bunch of links, and no guarantee when they become unavailable
So just for a health check, we can write a GitHub action to check link health every month, etc.
Here is a blog to get started: https://bhupesh-v.github.io/areyouok-keep-your-urls-healthy-github-actions-golang/

If you know any better ways to to this, feel free to comment below

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jarmos-san** [comment]
Took a look at your blog, it's a great project! I think we should proceed with your "areyouok" for now & we can reevaluate our needs once the the wiki is way too big or the GitHub Action environment times out.

**Comment by Bhupesh-V** [comment]
Cool, marking it as beginner-friendly to encourage contributions 👨🏽‍💻

**Comment by HanakoK9** [comment]
Hello, I'd like to work on this issue

**Comment by Bhupesh-V** [comment]
> Hello, I'd like to work on this issue

Cool, reach out if any help/advice required

**Comment by Jarmos-san** [comment]
> Hello, I'd like to work on this issue

@HanakoK9 thanks for taking the initiative! ❤️ 

Here's some heads up for you:

1. You need to add a GitHub Action ([official docs for reference](https://docs.github.com/en/actions)) which should be scheduled to execute at certain times. You can refer to the "[scheduled events](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule)" sections of the official docs for more reference.

2. @Bhupesh-V 's article he shared above has an example of how to create the said GitHub Action.

And of course, if you require more assistance feel free to reach out to comment/reach out to us.

**Comment by Bhupesh-V** [comment]
Closed via #27
