### ISSUE TITLE
Resources to get started in cybersecurity

### ISSUE THREAD

**Issue by asce-21** [developersIndia/wiki#35]
### Have you read the contributing guidelines for proposing a wiki?

- [X] I have read the contributing guidelines.

### What's this proposal about? What should this wiki cover? Who's the audience?

This is list of resources to get started in cybersecurity. This will cover roadmap for new comers to get started in cybersecurity domain by learning web application hacking.

This is my post which i want to contribute to wiki.

https://asce-21.github.io/2024/03/03/resources-to-get-started-in-cybersecurity.html

### Choose the category for this wiki

Community Guide

### Are you interested in authoring this wiki guide?

Yes

### Code of Conduct

- [X] I agree to follow the community's Code of Conduct

**Comment by Bhupesh-V** [comment]
@asce-21 This looks great, feel free to create a write-up via a PR.

Also, if possible, please check if we can include some high-quality threads from the forum https://www.reddit.com/r/developersIndia/search/?q=cybersecurity&type=link
