### ISSUE TITLE
How Indian developers land the top remote jobs in the world

### ISSUE THREAD

**Issue by nityeshaga** [developersIndia/wiki#37]
### Have you read the contributing guidelines for proposing a wiki?

- [X] I have read the contributing guidelines.

### What's this proposal about? What should this wiki cover? Who's the audience?

Everyone who works at a remote job has a unique story. It's not enough to just do Leetcode or prepare like a FAANG. This wiki will should cover real examples of people who are working remote jobs and exactly how they got it. 

Audience is developers with 1-3 years of experience who want to work top remote jobs.

### Choose the category for this wiki

Community Guide

### Are you interested in authoring this wiki guide?

Yes

### Code of Conduct

- [X] I agree to follow the community's Code of Conduct

**Comment by Jarmos-san** [comment]
@nityeshaga are you interested in authoring this contribution?

**Comment by nityeshaga** [comment]
Hey @Jarmos-san yes I would love to. I've got a lot of ideas based on the [interviews](https://www.youtube.com/@BeyondtheBrackets) i've been having with remote Indian devs.

**Comment by Jarmos-san** [comment]
Alright then, please go ahead and share a PR. You can also join us on Discord if you want to discuss about the contributions further.

**Comment by nityeshaga** [comment]
Do you have a link for the discord?

**Comment by Jarmos-san** [comment]
Here's the invite link - https://discord.com/invite/developersindia-669880381649977354

**Comment by nityeshaga** [comment]
I'm in that discord (nityeshaga). Is there a specific channel for discussing this wiki?
