### ISSUE TITLE
 Typo in the guide to find small foss projects

### ISSUE THREAD

**Issue by MohamedHalith001** [developersIndia/wiki#45]
### What Happened?

I went through the guide "[Discovering Small GitHub Projects for Contributing to FOSS](https://wiki.developersindia.in/faqs/finding-small-foss-projects-on-github#discovering-small-github-projects-for-contributing-to-foss)" and found a typo in the section [You chance for being an early adopter](https://wiki.developersindia.in/faqs/finding-small-foss-projects-on-github#you-chance-for-being-an-early-adopter).

Mistake : 
You never know what projects on github might get some traction over the years. If you participate in contributing to small FOSS consistenly, its possible that you might eventually become one of the maintainers.

The word consistently is misspelled here. The correct phrase should be

You never know what projects on GitHub might get some traction over the years. If you participate in contributing to small FOSS consistently, its possible that you might eventually become one of the maintainers.

![image](https://github.com/developersIndia/wiki/assets/69855107/a30c80bc-57f0-4c06-aa65-1caf76888b7e)

### What Browsers Are You Seeing the Problem On?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MohamedHalith001** [comment]
I can work on it, if possible

**Comment by Jarmos-san** [comment]
Yes, please go ahead and create a PR.

**Comment by triach-rold** [comment]
PR seems good to me

**Comment by Jarmos-san** [comment]
Fixed in #46
