### ISSUE TITLE
Tips for Succeeding at Hackathons

### ISSUE THREAD

**Issue by SujalChoudhari** [developersIndia/wiki#50]
### Have you read the contributing guidelines for proposing a wiki?

- [X] I have read the contributing guidelines.

### What's this proposal about? What should this wiki cover? Who's the audience?

1. The proposal is about adding an article about "Tips for Succeeding at Hackathons". I have won various Mumbai level hackathons, and National Level hackathons. I have some tips to share with the community.
2. This wiki covers, right from team formation, choosing topic and to presenting.
3. Any college student who want's to participate in a hackathon.

### Choose the category for this wiki

Community Guide

### Are you interested in authoring this wiki guide?

Yes

### Code of Conduct

- [X] I agree to follow the community's Code of Conduct

**Comment by Bhupesh-V** [comment]
@SujalChoudhari Looks like a good wiki addition, please go ahead with the first draft. Let us know if you need any help.

**Comment by SujalChoudhari** [comment]
On it.
Do I directly submit a pull request of draft?

**Comment by Bhupesh-V** [comment]
> On it. Do I directly submit a pull request of draft?

Yes, you can also create a [draft pr](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#converting-a-pull-request-to-a-draft), if you need early feedback before the final review.

**Comment by SujalChoudhari** [comment]
Sure. I will write the draft sometime today or tomorrow.
