### ISSUE TITLE
Add gamedev and CG resources

### ISSUE THREAD

**Issue by 9HarshAgarwal** [developersIndia/wiki#6]
Especially Blender, Godot, and open source books. Also, ArmorPaint, Armory, UPBGE and <other dozen open source projects mentioned by Games From Scratch> can be added, though I'm not up to date on those.

**Comment by BlackGoku36** [comment]
CG resources are here: https://github.com/developersIndia/wiki/pull/18
Don't think anyone is going to be interested in Armory or UPBGE nowadays
